version: '3.7'
services:
  nodejs:
    image: node:12
    network_mode: host
  social_metrics_db:
    container_name: sm_db
    env_file:
      - .pg/.env
    image: postgres:13
    ports:
      - 5405:5432
    volumes:
      - ./.pg:/docker-entrypoint-initdb.d/
      - pg_data:/var/lib/postgresql/data/pgdata
    restart: always
  social_metrics_nginx:
    image: nginx
    container_name: sm_nginx
    volumes:
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8088:8088
    network_mode: host
volumes:
  pg_data:

